### ISSUE TITLE
MPS()

### ISSUE THREAD

**Issue by XianruiWang** [onolab-tmu/TFLCbeamformer#1]
Dear Author, 

When I ran the code, an error came across. There is no built-in function MPS() in my Matlab.
I just wonder is this a Matlab built function or user defined one. Could you please attach this function as well?

Best regards

**Comment by KoueiYamaoka** [comment]
Dear theLittleTiger,

MPS() is a user-defined function, which was replaced by calcBFM(). I fixed this issue.
Thank you for letting me know.
